### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The getter 'latitude' was called on null.

### ISSUE THREAD

**Issue by afreen009** [romanejaquez/flutter_locationupdates#5]
Im not able to get route between source and destination. the error is

D/BufferQueueProducer( 7109): [SurfaceTexture-0-7109-0](this:0x7abe9af000,id:0,api:1,p:442,c:7109) cancelBuffer: slot 0
D/BufferQueueProducer( 7109): [SurfaceTexture-0-7109-0](this:0x7abe9af000,id:0,api:1,p:442,c:7109) cancelBuffer: slot 0
V/PhoneWindow( 7109): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@4b2d295, this = DecorView@8b3faa[MainActivity]
E/flutter ( 7109): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'latitude' was called on null.
E/flutter ( 7109): Receiver: null
E/flutter ( 7109): Tried calling: latitude
E/flutter ( 7109): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 7109): #1      MapPageState.showPinsOnMap (package:sidebaranimationflutter/Map/map.dart:144:28)
E/flutter ( 7109): #2      MapPageState.build.<anonymous closure> (package:sidebaranimationflutter/Map/map.dart:130:17)
E/flutter ( 7109): #3      _GoogleMapState.onPlatformViewCreated (package:google_maps_flutter/src/google_map.dart:317:14)
E/flutter ( 7109): #4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
E/flutter ( 7109): #5      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 7109): #6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 7109): #7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter ( 7109): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter ( 7109): #9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter ( 7109): #10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter ( 7109): #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
E/flutter ( 7109): #12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
E/flutter ( 7109): #13     GoogleMapController.init (package:google_maps_flutter/src/controller.dart)
E/flutter ( 7109): #14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
E/flutter ( 7109): #15     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 7109): #16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 7109): #17     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter ( 7109): #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter ( 7109): #19     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter ( 7109): #20     Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter ( 7109): #21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
E/flutter ( 7109): #22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
E/flutter ( 7109): #23     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter ( 7109): #24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
E/flutter ( 7109): #25     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 7109): #26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 7109): #27     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter ( 7109): #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter ( 7109): #29     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter ( 7109): #30     Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter ( 7109): #31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
E/flutter ( 7109): #32     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 7109): #33     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 7109): #34     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 7109): #35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 7109): #36     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 7109): #37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 7109):

**Comment by Silerqin** [comment]
hi, I also have this error. Did you solved it?

**Comment by devanshdixit** [comment]
can you explain more because I am not able to understand where are you getting the error from.
